CPP_DEBUG=g++ -std=c++14 -Wall -Werror -O0

list: list_user.cpp list.cpp copyassign.cpp copyconstructor.cpp moveassign.cpp moveconstructor.cpp destructor.cpp
	$(CPP_DEBUG) -o list list_user.cpp list.cpp copyassign.cpp copyconstructor.cpp moveassign.cpp moveconstructor.cpp destructor.cpp
